### ISSUE TITLE
why *= 1.2 for yolo detection result?

### ISSUE THREAD

**Issue by YuhaoYeSteve** [ZQPei/deep_sort_pytorch#43]
Line 40 in demo_yolo3_deepsort.py: bbox_xywh[:,3] *= 1.2. Can I ask why multiply 1.2 for height of yolo detection result?

**Comment by ZQPei** [comment]
The detected bbox of pedestrain is not that accurate because the yolo detector is not trained for pedestrain dataset. That lead to the bbox often smaller than it should be. So I multiply bbox's width or height by 1.2 to make the bbox large enough to bound the whole person, which is also helpful to feature extractor in deep sort.

**Comment by YuhaoYeSteve** [comment]
got it, thanks!

**Comment by czy-orange** [comment]
@ZQPei Hi, I wonder if this is your own idea? I did not see it in original paper or deep_sort tensorflow repo. BTW, do you think it will causes w to be wider than the image width? In my project, I met a problem that sometimes the bbox coordinate is minus. Thanks.
